#2
"""
Write a guess word game that randomly generates a word and prompts the user to
guess one letter at a time, as shown in the sample run. Each letter in the word is
displayed as an asterisk. When the user makes a correct guess, the actual letter is
then displayed. When the user finishes a word, display the number of misses and ask
the user whether to continue playing.
"""
from random import shuffle


class GuessWord:
    __words = [
        "apple", "river", "lantern", "galaxy", "mountain", "whisper", "thunder", "meadow",
        "comet", "canyon", "blossom", "notebook", "ember", "fortress", "mosaic", "horizon",
        "vertex", "spiral", "eclipse", "harbor", "orchard", "tapestry", "glacier", "summit",
        "prism", "cipher", "voyage", "crest", "biscuit", "quartz", "falcon", "syllabus",
        "nectar", "palette", "brigade", "groove", "rhythm", "novel", "portrait", "beacon",
        "cobalt", "anthem", "vignette", "caravan", "harp", "ledger", "marigold", "nebula",
        "oasis", "pollen", "quill", "relic", "saffron", "timber", "utopia", "vector",
        "willow", "yonder", "zephyr", "alcove", "boulder", "cascade", "drift", "furrow",
        "garrison", "hearth", "isobar", "jigsaw", "kelp", "lattice", "myrtle", "nosegay",
        "obelisk", "papyrus", "quay", "rendezvous", "sonnet", "trough", "umbra", "valence",
        "waltz", "xylophone", "yacht", "zircon", "alabaster", "bridle", "carafe", "dervish",
        "estuary", "frieze", "gavel", "hiatus", "incisor", "jetty", "kiosk", "lullaby",
        "menhir", "noggin", "opal", "pylon"
    ]  # List of words generated by Co-Pilot (prompt: "generate a python list with 100 random words (not prepositions)")

    __chosen_word = None
    __masked_word = None
    __guess = None
    __game = True

    __wrong_guesses = 0

    def __init__(self):
        # Choose word using random.shuffle
        self.select_word()

    def select_word(self):
        # Randomize the list, then select the first word
        shuffle(self.__words)
        self.__chosen_word = self.__words[0]
        self.__masked_word = "*" * len(self.__chosen_word)

    def play_game(self):
        # Run the game in a while loop
        while self.__game:
            guess = str(input(f"(Guess) Enter a letter in word {self.__masked_word} > ")).lower()

            # Verify if Guess is valid
            if len(guess) != 1:
                print(f"Invalid Guess: {guess}. Guess needs to be 1 character long.")
                continue

            # Verify if it's not repeated character
            if guess in self.__masked_word:
                print(f"{guess} is already in the word")
                continue

            # Is your guess right?
            if guess in list(self.__chosen_word):
                for i, char in enumerate(self.__chosen_word):
                    if char == guess:
                        replace_list = list(self.__masked_word)
                        replace_list[i] = self.__chosen_word[i]
                        self.__masked_word = ''.join(replace_list)

                # Does your guess end the game?
                if self.__masked_word == self.__chosen_word:
                    self.win_game()
                continue
            else:
                print(f"{guess} is not in the word")
                self.__wrong_guesses += 1
                continue

        print("Thank you for playing!")

    def win_game(self):
        plural = 's' if self.__wrong_guesses != 1 else ''
        print(f"The word is {self.__masked_word}. You missed {self.__wrong_guesses} "
              f"time{plural}\n")

        # Play Again?
        play_again = str(input("Do you want to guess another word? Enter y or n> ")).lower()
        while play_again not in ["y", "n"]:
            play_again = str(input(f"{play_again} is not a valid response.\n"
                                   f"Do you want to guess another word? Enter y or n> ")).lower()

        if play_again == 'y':
            # Re-setting the game
            self.select_word()
            self.__wrong_guesses = 0
            self.play_game()

        else:
            self.__game = False


GuessWord().play_game()
